### ISSUE TITLE
validate-lessons.sh script fails

### ISSUE THREAD

**Issue by blinklet** [nre-learning/nrelabs-curriculum#228]
The `validate-lessons.sh` script does not download the syring file and also looks for lessons in the wrong directory.

You assume that the "`jq`" package is installed and that is not the case on my Ubuntu 18.04 desktop. Your documentation should ask users to install `jq` first (or check for it in the script).

We need to install the `jq` package first:

```
sudo apt -y install jq
```

Then, when the script does run (after installing jq), it does not find any lessons.

```
INFO[0000] Imported 0 lesson definitions.               
All detected lesson files imported successfully.
```

I looked at the script and, is it looking in the right directory? The last line seems to be looking for a directory named `antidote`. 

But, when I ran the `syrctl` command using the exiting directory structure, I still see the same results.

```
blinklet@T420:~/nrelabs-curriculum$ ./syrctl validate ../antidote
INFO[0000] Imported 0 lesson definitions.               
All detected lesson files imported successfully.
blinklet@T420:~/nrelabs-curriculum$ ./syrctl validate
INFO[0000] Imported 0 lesson definitions.               
All detected lesson files imported successfully.
blinklet@T420:~/nrelabs-curriculum$ ./syrctl validate ../
INFO[0000] Imported 0 lesson definitions.               
All detected lesson files imported successfully.
blinklet@T420:~/nrelabs-curriculum$ ./syrctl validate .
INFO[0000] Imported 0 lesson definitions.               
All detected lesson files imported successfully.
blinklet@T420:~/nrelabs-curriculum$ ./syrctl validate ./lessons/
INFO[0000] Imported 0 lesson definitions.               
All detected lesson files imported successfully.
blinklet@T420:~/nrelabs-curriculum$ ./syrctl validate ./lessons/fundamentals/
INFO[0000] Imported 0 lesson definitions.               
All detected lesson files imported successfully.
blinklet@T420:~/nrelabs-curriculum$ 
```

**Comment by Mierdin** [comment]
So, there's a few things going on here. First and foremost, this script isn't meant to be user-run. Users can continue to use `syrctl` directly - this is a CI tool.

It's true that the script needs to be updated to look in the correct directory, but more than that, it needs to use a much more recent build of Syringe. We run into this issue sometimes where the curriculum is updated structurally, and the latest tagged version of Syringe doesn't work, so you need to compile from `master`. I'll finish getting nightly builds working, and move to using that instead of downloading the latest tagged version, and it should be able to validate lessons.

> Your documentation should ask users to install jq first 

Again, this script is meant to be pretty static so lesson content is validated in CI, it's not meant to be run directly by users, so I'll make that more clear. For now, to validate lesson content yourself, please use `syrctl` - either the latest docker image, or compile from source.

**Comment by Mierdin** [comment]
Actually it turns out to be an even simpler answer. This script isn't used any more. The [travis config](https://github.com/nre-learning/nrelabs-curriculum/blob/master/.travis.yml#L8) now uses the latest syringe docker image to perform lesson validation, and does so correctly (you can see this working in one of the [recent curriculum builds](https://travis-ci.org/nre-learning/nrelabs-curriculum/builds/533151533).

I deleted this script in 24d5186, so I'll close this now.
