### ISSUE TITLE
Issues in stackstorm lesson

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/nrelabs-curriculum#256]
Looks like any action involving the `napalm` pack produces something along the lines of:

```
no module named copyable_regex_object
```

The st2 image probably needs to get an updated dependency and rebuilt.

Also, a much more minor issue, but the `cli` in stage 2 is unnecessary.

**Comment by cloudtoad** [comment]
I am not able to reproduce this with a fresh pull of the curriculum from master.  All the napalm snippets are working on my local machine.

Also, see [this change to textfsm](https://github.com/google/textfsm/commit/2a32ff6edf4915e5477c229c83196dfb81d44f89)

**Comment by cloudtoad** [comment]
If I were to hazard a guess, I'd say the issue was netmiko.  They fixed it 27 days ago.  In a fresh virtualenv, if you install the python packages from requirement.txt in the nre-learning/stackstorm-napalm repository, the only file that imports "copyable_regex_object" is a modified version of _clitable.py (which is originally from the textfsm package) in netmiko.

See [here](https://github.com/ktbyers/netmiko/commit/ef77e21e0b52317ccce66c2d4a707d0890ff05ae)

But the v1.0.0 and v0.4.0 tagged stackstorm images are from 13 or 15 days ago on docker hub.  So those should be working.  At least, it appears that way locally when I tried just now.

**Comment by cloudtoad** [comment]
Ok... I was able to reproduce the issue, and indeed this is the problem.  I think all we need to do is rebuild the docker image and it'll work.  Testing now...

**Comment by cloudtoad** [comment]
Temporary fix:  Point lesson at cloudtoad/stackstorm docker image which works until we can do another nightly build of the images.

**Comment by Mierdin** [comment]
Nothing's consuming the `latest` version of the image at the moment. A PR to address the problem in the source of the image here: https://github.com/nre-learning/nrelabs-curriculum/tree/master/images/st2 will result in the corrected version being built when we get around to doing nightlys. So please follow up with a PR that includes your changes to that source material.

**Comment by Mierdin** [comment]
To clarify after private discussion, looks like this was actually just a point-in-time problem. This will likely resolve itself when we start doing nightly builds (hopefully soon) but what we should also do is fine-tune the requirements.txt file to be more specific, so that it matters less when we happen to run the build.

I'll keep this issue open until a PR is submitted to address this.

**Comment by cloudtoad** [comment]
See [PR #2](https://github.com/nre-learning/stackstorm-napalm/pull/2) in the [nre-learning/stackstorm-napalm](https://github.com/nre-learning/stackstorm-napalm) repository.

Updated requirements.txt file with entry "netmiko>=2.4.1"

**Comment by Mierdin** [comment]
We're doing nightly builds now, and can confirm this is fixed in the latest image builds, now that the pack requirements.txt is fixed. Thanks @cloudtoad.

I'll close this issue since there's nothing left to do - this will make it to prod the next time we cut a release.
