### ISSUE TITLE
Non responsive images in the Terraform & Junos lesson

### ISSUE THREAD

**Issue by jessicagarrison** [nre-learning/nrelabs-curriculum#318]
In the Terraform & Junos lesson, there are images that are not responsive in part 1.  
WRITE/PLAN/CREATE

![Screen Shot 2020-03-31 at 8 40 42 PM](https://user-images.githubusercontent.com/15332231/78106703-c2e97080-73a8-11ea-9b57-ffed961b742c.png)

**Comment by Mierdin** [comment]
Turns out I was wrong to ask you to open this in the `nre-styles` repo. I mistakenly thought we didn't have a class to do what I wanted, but it turns out we do. I applied this to the image in the curriculum in https://github.com/nre-learning/nrelabs-curriculum/pull/317/commits/55608174e93ec38d6284b9456a476a0bfa6d5559, and it will get fixed when we roll the 0.6.0 compatibility updates into the curriculum.

Thanks for this!
